@startuml class_system_io
title "Class Diagram System IO"

hide <<DataModel>> members
package DataModel {
    class TreeItem <<DataModel>>
    class ObjectFactory <<DataModel>>
}

namespace gurps_system {

class Io {
+ Io(factory: ObjectFactory&)
-- Serializer management --
+ install(serializer: shared_ptr<Serializer>): bool
+ uninstall(id: uuid): bool
+ installedSerializers(): uuid[]
-- Serializer lookup --
+ serializer(id: uuid): Serializer*
+ serializer(filter: string): Serializer*
+ allFilters(): QStringList
}

gurps_system.Io o-- DataModel.ObjectFactory

abstract class Serializer {
+ Serializer()
-- Identity --
+ {abstract} id(): uuid
-- Capabilities --
+ {abstract} filters(): QStringList
+ {abstract} provides(filter: QString): bool
+ {abstract} canRead(firstLine: QByteArray): bool
-- IO --
+ {abstract} read(stream: QIODevice, factory: ObjectFactory): shared_ptr<TreeItem>
+ {abstract} write(stream: QIODevice, obj: TreeItem): void
}

gurps_system.Io "1" *-- "*" gurps_system.Serializer

class JsonSerializer
gurps_system.Serializer <|-- gurps_system.JsonSerializer

class XmlSerializer
gurps_system.Serializer <|-- gurps_system.XmlSerializer

class LatexSerializer
gurps_system.Serializer <|-- gurps_system.LatexSerializer

}

@enduml